### ISSUE TITLE
Resource Pack doesn't download

### ISSUE THREAD

**Issue by thomaboehi** [Phoenix616/ResourcepacksPlugins#35]
I configured it like that:

```
  heridia:
    url: http://boehi.xyz/Heridia.zip
    hash: ed12f08884db3c8818746b5ba3fc85a80eb63c38
    format: 0
    restricted: false
    permission: resourcepacksplugin.pack.heridia
```

And when I join, it shows a download screen but 0.05 secondes only, then disappears and nothing changes. Even if I use /usepack, it does the same.
