### ISSUE TITLE
Startup-warn: No default config 'languages/lang.de.yml' found in Jar

### ISSUE THREAD

**Issue by RedstoneFuture** [Phoenix616/ResourcepacksPlugins#46]
#### Used Version
1.8.3-SNAPSHOT (build 377)
 
 
#### Config

 ```yaml
debug: false
# Default language
default-language: de
# Disable all metrics included in this plugin.
disable-metrics: false
# Whether or not resourcepack file hashes should be generated on startup:
autogeneratehashes: false
# Whether /usepack should apply packs temporary or permanent when run without any argument:
usepack-is-temporary: false
# Whether packs that a player has stored will override a matched assignments
stored-packs-override-assignments: false
# When manually setting a permanent pack then it will be reset if the user disconnects in under x amount of seconds.
# 0 or anything below will disable this functionality
permanent-pack-remove-time: 30
packs: [...]
 ```
 
 
#### Full Log
```
[17:35:23] [main/WARN] [BungeeResourcepacks]: No default config 'languages/lang.de.yml' found in BungeeResourcepacks.jar!
[17:35:23] [main/INFO] [BungeeResourcepacks]: Found locale de!
```

#### What is happening?
You get an WARN at the startup. It's unlucky, because in this situation it's not a problem.

#### What did you expect to happen?
Can you change this startup info from a `[main/WARN]` to a `[main/INFO]`, please? Or you hide these message if the DEBUG option is `false`.

#### Additional context
The language messages in DE work fine.
