### ISSUE TITLE
[FIXED] Sending Wrong resource packs

### ISSUE THREAD

**Issue by nix-007** [Phoenix616/ResourcepacksPlugins#47]
```
  gamepack:
    variants:
    - url: https://www.dropbox.com/s/7v60qh52ysekv4o/new.zip?dl=1
      hash: bb97164a572c9790541088a6e02ce803f60e52be
      format: 6
      version: '1.16'
      restricted: `false`
      permission: worldresourcepacks.pack.gamepack-variant-1
      variants: null
    - url: https://www.dropbox.com/s/bwez9ofhg3hw0y5/legacy_cvcmar17zip.zip?dl=1
      hash: c00ceeb39916f930cc8ec9f8e529bb059cc3deac
      format: 1
      version: '1.8'
      restricted: false
      permission: worldresourcepacks.pack.gamepack-variant-2
      variants: null
    restricted: false
    permission: worldresourcepacks.pack.gamepack
```
    
    this does not check the version it just sends the first variant always
