### ISSUE TITLE
Decline message keeps sending every world change

### ISSUE THREAD

**Issue by SirKillian** [Phoenix616/ResourcepacksPlugins#48]
#### Used Version

 1.10.10
 
#### Config

 ```yaml
# Assignment section for the whole server. (Per worlds assignments override these settings)
global:
  pack: StickyPack
  send-delay: 10
  actions:
    declined:
      message: |-
        &c&lWarning:
        &c  You have declined to use our resourcepack.
        &c  We have 250+ custom items that you wont be able to see.
        &7
        &c  If you wish to enable our resourcepack visit
        &a  &a&nhttps://stickymc.com/StickyPack
    loaded:
      message: "&7&oResourcepack successfully loaded."
  first-join-actions:
    declined:
      message: |-
        &c&lWarning:
        &c  You have declined to use our resourcepack.
        &c  We have 250+ custom items that you wont be able to see.
        &7
        &c  If you wish to enable our resourcepack visit
        &a  &a&nhttps://stickymc.com/StickyPack
    loaded:
      message: "&7&oResourcepack successfully loaded."
 ```
 
#### Environment description

Tuinity 1.16.4
Java 11
 
#### What is happening?

When a player declines the resource pack and we send them a declined message, it sends the message to the player every single time they change worlds...

#### What did you expect to happen?

It should not send the decline message every single time they change worlds.

#### Additional context

![](https://sirkillian.gg/i/f84jlah0kiri20oy.png)
