### ISSUE TITLE
BungeeResourcePacks Causing Preview Snapshot Client to be Disconnected

### ISSUE THREAD

**Issue by Xuwznln** [Phoenix616/ResourcepacksPlugins#49]
#### Used Version
BungeeResoourcepacks dev build 361 and 386.

#### Config

 ```yaml
debug: true
default-language: en
disable-metrics: true
autogeneratehashes: true
usepack-is-temporary: true
stored-packs-override-assignments: false
permanent-pack-remove-time: 30
packs:
  scia:
    url: https://*.zip
    hash: d68f179e5366ba8d3e7a680a2ab6a45ab2879090
    format: 4
    restricted: false
    permission: bungeeresourcepacks.pack.lobbypack
  ra:
    url: https://*.zip
    hash: bfc64572e5343e4008b87af5049663d3054218aa
    restricted: false
    permission: bungeeresourcepacks.pack.lobbypack
empty:
  url: https://*.zip
  hash: 67256f3a3daa33bb8e4daa81e81a3631c5158fc7
global:
  secondary:
  - scia
  - ra
  send-delay: 20
servers:
  survival:
    pack: scia
    regex: Survival.*
  rts:
    pack: ra
    regex: RTS.*
 ```
 
#### Environment description
Waterfall with 1.17 support version. (link: https://github.com/PaperMC/Waterfall/pull/582)
 
#### Full Log

```
No error log, simply disconnect info.
```

#### What other programs/plugins are you running?
I have a plugin created by myself to prevent snapshot clients use resourcepacks, here is the main part code.
 ```java
    @EventHandler
    public void on(ResourcePackSelectEvent e){
        if(e.getStatus()==SUCCESS){
            if(proxyServer.getPlayer(e.getPlayerId()).getPendingConnection().getVersion()>=1073741829){
                e.setStatus(WRONG_VERSION);
            }
        }
    }
```

#### What is happening?
Preview snapshot client will disconnect when his potion effect is expired. I have no idea why this would happen. But after I remove brp, they can play normally. This happens on all downstream servers whether it is fabric or paper servers with viaversion-dev-21w03a.
