### ISSUE TITLE
Plugin sends empty pack instead of the assigned pack

### ISSUE THREAD

**Issue by IIJJ22GG** [Phoenix616/ResourcepacksPlugins#52]
I'm trying to make the plugin send a different resource pack depending on the dimension the player is in, so I set the "worlds" setting in the YML to

`global:
  pack: overworldpack
  send-delay: 1
worlds:
  world:
    pack: overworldpack
  world_nether:
    pack: netherpack
  world_the_end:
    pack: endpack`

I logged into the server, and absolutely nothing happened, not even when changing my dimension. I can load the packs using commands just fine, but when I change my dimension, the pack first unloads, then loads the empty pack. Do I have it set up improperly?

**Comment by Phoenix616** [comment]
Please provide your full config as well as log.

**Comment by IIJJ22GG** [comment]
Sure.

```YML
debug: true
default-language: en
disable-metrics: false
autogeneratehashes: false
usepack-is-temporary: true
stored-packs-override-assignments: false
permanent-pack-remove-time: 30
packs:
  overworldpack:
    url: https://www.dropbox.com/s/58s1zq020h76470/VanillaChanges-Overworld.zip?dl=1
    format: 5
    restricted: true
    permission: worldresourcepacks.pack.owp
    hash: 9b8fa61b94dadfc03345564d1c340627ae03f9e0
  netherpack:
    url: https://www.dropbox.com/s/k0l1ytrur3d8yiv/VanillaChanges-Nether.zip?dl=1
    format: 5
    restricted: true
    permission: worldresourcepacks.pack.np
    hash: 54072fe457e377ee3bac12cf043904a5fcd5a264
  endpack:
    url: https://www.dropbox.com/s/hxamqbs5vb392es/VanillaChanges-End.zip?dl=1
    format: 5
    restricted: true
    permission: worldresourcepacks.pack.ep
    hash: a0fa40956520282787b249591f19e65b1ed1d04e
empty:
  url: http://cdn.moep.tv/files/Empty.zip
  hash: 01517226212d27586ea0c5d6aff1aa5492dd2484
global:
  pack: overworldpack
  send-delay: 1
worlds:
  world:
    pack: overworldpack
  world_nether:
    pack: netherpack
  world_the_end:
    pack: endpack
```

[latest.log](https://github.com/Phoenix616/ResourcepacksPlugins/files/5953954/latest.log)
