### ISSUE TITLE
pack wont load when moving to the server

### ISSUE THREAD

**Issue by eXstremgamin360** [Phoenix616/ResourcepacksPlugins#76]
I have two worlds, world A and world B. I want a reasource pack in only world B. if i was in world B when i left the server and I join again, putting me into world B the resource pack will be downloaded and applied. But if im already in the server and and I go from world A to world B the pack isnt loaded.

here is my config file:

```yaml
debug: true
default-language: en
disable-metrics: false
autogeneratehashes: true
append-hash-to-url: true
usepack-is-temporary: true
stored-packs-override-assignments: false
permanent-pack-remove-time: 30
use-auth-plugin: false
empty:
  url: http://cdn.moep.tv/files/Empty.zip
  hash: 01517226212d27586ea0c5d6aff1aa5492dd2484
global:
  optional-packs:
  - lobbypack
servers:
  CraftyCannoneers:
    pack: craftycannoneers
    send-delay: 10
packs:
  lobbypack:
    url: http://example.com/lobbyresourcepack.zip
    hash: abcdef012345678abcdef012345678abcdef0123
    format: 1
    version: '1.8'
    restricted: false
    permission: bungeeresourcepacks.pack.lobbypack
  gamepack:
    restricted: false
    permission: bungeeresourcepacks.pack.gamepack
    variants:
    - url: http://example.com/minigameresourcepack_1_15.zip
      hash: 012345678abcdef012345678abcdef012345678a
      format: null
      version: '1.15'
      restricted: false
      permission: bungeeresourcepacks.pack.gamepack-variant-1
      type: null
      variants: null
    - url: http://example.com/minigameresourcepack_1_12.zip
      hash: 012345678abcdef01234567dddcdef012345678a
      format: null
      version: '1.12'
      restricted: false
      permission: bungeeresourcepacks.pack.gamepack-variant-2
      type: null
      variants: null
  Craftycannoneers:
    url: https://www.dropbox.com/s/x4ykrxo6ldabch0/resources.zip?dl=1
    hash: b69a9af576a39c5c94be9c45753b15a3d3a3a438
    restricted: false
    permission: resourcepacksplugin.pack.craftycannoneers
```
