### ISSUE TITLE
Unloading a pack does not work

### ISSUE THREAD

**Issue by jandie1505** [Phoenix616/ResourcepacksPlugins#81]
#### Used Version

 latest (on August 2, 2023)
 
#### Config
<details>
          <summary>Config</summary>

 ```yaml
debug: true
# Default language
default-language: en
# Disable all metrics included in this plugin.
disable-metrics: false
# Whether or not resourcepack file hashes should be generated on startup:
autogeneratehashes: false
# Whether to append the pack hash to the end of the URL of the pack like url#hash.
# This is necessary to work around a Vanilla bug which prevents changed packs from being downloaded
# properly again: https://bugs.mojang.com/browse/MC-164316
append-hash-to-url: true
# Whether /usepack should apply packs temporary or permanent when run without any argument:
usepack-is-temporary: true
# Whether packs that a player has stored will override a matched assignments
stored-packs-override-assignments: false
# When manually setting a permanent pack then it will be reset if the user disconnects in under x amount of seconds.
# 0 or anything below will disable this functionality
permanent-pack-remove-time: 30
# Whether to only send packs if authenticated on the Minecraft server
# Requires WorldResourcepacks to be installed on the Minecraft server too
use-auth-plugin: false
# Different packs can be defined in this section
packs:
  acm2:
    url: '<url>'
    hash: '<hash>'
    format: 13
    restricted: false
  #lobbypack:
  # # The url the client should download the resourcepack from.
  # # Has to be a direct download link! No mediafire/mega/other oneclick-hoster!
  #  url: http://example.com/lobbyresourcepack.zip
  # # The sha1 hash of the resourcepack's zip file,
  # # if not correct the client will waste bandwidth but it will still work!
  # # At least that's what the Minecraft wiki says... (Site: Server.properties#Minecraft_server_properties)
  #  hash: abcdef012345678abcdef012345678abcdef0123
  # # The format version of this resourcepack
  #  format: 1
  # # Directly define the Minecraft version instead of the format
  # # Supports string representation of the versions and protocol numbers
  # # You don't need to define both the version and the format (if so then the highest one will take effect)
  #  version: "1.8"
  # # Whether or not this pack will only be send to players with a certain permission
  # # permission: bungeeresourcepacks.pack.<packname>
  #  restricted: false
  # # If you want you can define a specific permission for this pack if you don't want
  # # the default bungeeresourcepacks.pack.<packname> permission!
  #  permission: bungeeresourcepacks.pack.lobbypack
  #gamepack:
  #  # Set different variants e.g. for different versions or permissions
  #  # This list supports all normal pack settings and is checked top to bottom.
  #  # The first one that matches the player will be used.
  #  variants:
  #  - url: http://example.com/minigameresourcepack_1_15.zip
  #    hash: 012345678abcdef012345678abcdef012345678a
  #    version: '1.15'
  #  - url: http://example.com/minigameresourcepack_1_12.zip
  #    hash: 012345678abcdef01234567dddcdef012345678a
  #    version: '1.12'
  # Define as many packs as you want
  #another_example_pack:
  #  url: http://example.com/another.zip
  #  hash: abcdef012345678abcdef012345678abcdef0123
# Empty pack to reset the pack to the default one
empty:
  url: '<url>'
  hash: '<hash>'
global:
  # Define a global pack:
  pack: ''
  # List of packs to not replace if the user already has them
  # If no main pack is set the first one also gets used to reset 
  # the pack if the user has a non-optional one
  # Also this list will be used to select a pack if a user does not have the permission
  # or the right version to use that pack. (From top to bottom)
  #optional-packs:
  #- lobbypack
  # Delay in ticks before sending the pack to a player after he logs in/switches to the server
  send-delay: 20
# Different servers with different packs can be defined here
servers:
  # Config for a server named "lobby"
  #lobby:
  #  pack: lobbypack
  #  optional-packs:
  #  - gamepack
  ACM2TDM:
    pack: 'acm2'
    # Use a regex to target all servers with a certain name
    regex: 'ACM2TDM-.*'
    send-delay: 20
  ACM2CTF:
    pack: 'acm2'
    regex: 'ACM2CTF-.*'
    send-delay: 20
  ACM2Rush:
    pack: 'acm2'
    regex: 'ACM2Rush-.*'
    send-delay: 20
  # Define as many servers as you want.
  # The name of the section is the server name unless a regex is specified.
  #another_example_server:
  #  pack: another_example_pack

 ```
 
</details>
 
#### Environment description

 - OS: Ubuntu 22.04 LTS Server
 - Bungee: Watetfall latest
 
#### Full Log
<details>
          <summary>Log</summary>

```log
[02.08 15:32:19.158] INFO: [Proxy-1] [15:32:18 INFO]: [/<ip>] <-> InitialHandler has connected
[02.08 15:32:20.157] INFO: [Proxy-1] [15:32:19 INFO]: [jandie1505|/<ip>] <-> ServerConnector [SilentLo
bby-1] has connected
[02.08 15:32:26.162] INFO: [Proxy-1] [15:32:25 INFO]: [jandie1505|dynamic-<ip>/<ip
] <-> ServerConnector [ACM2Rush-1] has connected
[02.08 15:32:26.162] INFO: [Proxy-1] [15:32:25 INFO]: [dynamic-<ip>/<ip>
|jandie1505] <-> DownstreamBridge <-> [SilentLobby-1] has disconnected
[02.08 15:32:27.163] INFO: [Proxy-1] [15:32:26 INFO] [BungeeResourcepacks]: [DEBUG] jandie1505 matched assignment ACM
2Rush due to main pack
[02.08 15:32:27.163] INFO: [Proxy-1] [15:32:26 INFO] [BungeeResourcepacks]: [DEBUG] Send pack acm2 (<url>) to jandie1505
[02.08 15:32:37.169] INFO: [Proxy-1] [15:32:36 INFO]: [jandie1505|dynamic-<ip>/<ip>
] <-> ServerConnector [SilentLobby-1] has connected
[02.08 15:32:37.170] INFO: [Proxy-1] [15:32:36 INFO]: [dynamic-<ip>/<ip>
|jandie1505] <-> DownstreamBridge <-> [ACM2Rush-1] has disconnected
```

</details>

#### What other programs/plugins are you running?

PartyAndFriends, Geyser-Bungeecord, Floodgate-Bungee, LiteBans, LuckPerms, PremiumVanish, RedisBungee, ReportSystem
(should all not affect resource packs)

#### What is happening?

Unloading packs via the empty pack is not working.
If a resource pack is loaded and I enter a server which has no resource pack, nothing happens.
If I use /resetpack <name> false, it shows that the pack '' was stored and that I have no pack or the empty one loaded (but I have one loaded). But if I then try to load the currently used pack with /usepack <name>, it shows the message that it is already loaded. But I cannot unload it with /resetpack altough the plugin knows that I have one loaded.

#### What did you expect to happen?

/resetpack or entering a server with no resource pack set will unload the resource pack (loading the empty one if one was previously loaded).

#### Additional context

![grafik](https://github.com/Phoenix616/ResourcepacksPlugins/assets/34031551/52ff0fad-aa68-4f65-8a53-8a86a767a828)
