### ISSUE TITLE
Empty packs does not load in 1.20+

### ISSUE THREAD

**Issue by Ente3** [Phoenix616/ResourcepacksPlugins#87]
### What is happening?

I have set up an empty pack for my global, so I can have a specific pack for subserve but on hub server non.
In 1.19+ everything is working alright but in 1.20 the normal packs aren't removed

### What did you expect to happen?

Packs from the subservers should be removed when join to hub servers

### Version

(latest dev build) 	Dec 16, 2023

### Config

```YAML
[Put the config here]
debug: true
default-language: en
disable-metrics: false
autogeneratehashes: true
append-hash-to-url: true
usepack-is-temporary: true
stored-packs-override-assignments: false
permanent-pack-remove-time: 30
use-auth-plugin: false
empty:
  url: http://185.239.236.86/baxnetzwerk-empty.zip
  hash: 41948CE940ECD37D9B8F601B4B2DEC27E6C683DA
  uuid: 327f2274-8656-33ae-8cd9-86ce1ec70c31
global:
  pack: empty
  send-delay: 20
servers:
  LuckyArena:
    pack: luckyarena_pack
    regex: DevServer.*
packs:
  luckyarena_pack:
    url: http://185.239.236.86/baxnetzwerk-luckyarena_V2.zip
    uuid: d3b811df-4ef6-38c0-a3d8-98263938287a
    hash: 50525CCCBB5A669AC01605762DA33494E4191B61
    restricted: false
    permission: bungeeresourcepacks.pack.luckyarena_pack
```

### Server/system Version

BungeeCord - FlamCord latest; Purpur 1.19.2

### Log

```shell
[14:12:28] [Netty Worker IO Thread #5/INFO]: Ente_3 executed command: /server DevServer-1
[14:12:30] [BungeeResourcepacks Pool Thread #4/INFO] [BungeeResourcepacks]: [DEBUG] Ente_3 matched assignment LuckyArena due to main packs
[14:12:30] [BungeeResourcepacks Pool Thread #4/INFO] [BungeeResourcepacks]: [DEBUG] Send pack luckyarena_pack (http://185.239.236.86/baxnetzwerk-luckyarena_V2.zip) to Ente_3
[14:12:42] [Netty Worker IO Thread #5/INFO]: Ente_3 executed command: /server Lobby-1
[14:12:44] [BungeeResourcepacks Pool Thread #4/INFO] [BungeeResourcepacks]: [DEBUG] Ente_3 matched assignment global due to main packs
[14:12:44] [BungeeResourcepacks Pool Thread #4/INFO] [BungeeResourcepacks]: [DEBUG] Removed pack luckyarena_pack (d3b811df-4ef6-38c0-a3d8-98263938287a) from Ente_3
```

### What other programs/plugins are you running?

TCPShield 2.7.0
LuckPerms-Bungee 5.4.119
AzLink
+ Self Code Plugins

**Comment by Phoenix616** [comment]
According to your log the plugin correctly removed your pack. Are you saying that even though you got that message you still have the luckyarena_pack applied?

If so then please test with the latest dev build as there have been several adjustments over the last months. Also please provide which client version you are using exactly as 1.20.3/4 behave differently than 1.20.2 or 1.20/.1.

**Comment by Ente3** [comment]
> According to your log the plugin correctly removed your pack. Are you saying that even though you got that message you still have the luckyarena_pack applied?
Yes exactly

> If so then please test with the latest dev build as there have been several adjustments over the last months. If it's still broken check your client's log and also please provide which client version you are using exactly as 1.20.3/4 behave differently than 1.20.2 or 1.20/.1.
I just tried with 1.20.2 and it's working as well
It seems like an 1.20.4 issue. Let me try 1.20.3

**Comment by Ente3** [comment]
Even if I try usepack empty etc. it's not working

**Comment by Phoenix616** [comment]
Please provide your full log including the startup.

**Comment by Logikoz** [comment]
@Phoenix616 i have same problem.

i have 7 servers in network, but only one have a custom resource-pack (RP).

but, when enter in custom RP server, and return to lobby (dont have custom RP), the same RP is applied on hub.

to solve this problem, i have downloaded default minecraft texture-pack, and applied in global pack.

see:
```yaml
debug: true
default-language: pt-br
disable-metrics: false
autogeneratehashes: true
append-hash-to-url: true
usepack-is-temporary: true
stored-packs-override-assignments: false
permanent-pack-remove-time: 30
use-auth-plugin: false
packs:
  mmorpg:
    url: https://download.mc-packs.net/pack/0488ea8fefa4484a4721e14ffcfaed050ce8cdbb.zip
    hash: 0488ea8fefa4484a4721e14ffcfaed050ce8cdbb
    uuid: 21234567-89ab-cdef-0123-456789abcdef
    format: 1
    version: "1.20"
    restricted: false
    permission: bungeeresourcepacks.pack.mmorpg
  default:
    url: https://download.mc-packs.net/pack/c51ae66ae3953b6c524ae58f27c5c28b814a9d45.zip
    hash: c51ae66ae3953b6c524ae58f27c5c28b814a9d45
    format: 1
    version: "1.20"
    restricted: false
    permission: bungeeresourcepacks.pack.default
global:
  pack: default
servers:
  survival_mmorpg:
    packs:
    - mmorpg
```

in log: 
`19:12:05 [INFO] [BungeeResourcepacks] [DEBUG] Logikoz matched assignment global due to main packs
19:12:05 [INFO] [BungeeResourcepacks] [DEBUG] Removed pack mmorpg (21234567-89ab-cdef-0123-456789abcdef) from Logikoz
19:12:05 [INFO] [BungeeResourcepacks] [DEBUG] Send pack default (https://download.mc-packs.net/pack/c51ae66ae3953b6c524ae58f27c5c28b814a9d45.zip) to Logikoz`

this solucion partially works, but have same problems...

hotbar when custom resource-pack (mmorpg)
![image](https://github.com/Phoenix616/ResourcepacksPlugins/assets/37851168/ce3a4968-26cd-4f4d-9bc3-10339c92df47)

hotbar after mmorpg texture-pack has removed, and applied default
![image](https://github.com/Phoenix616/ResourcepacksPlugins/assets/37851168/622bc83f-ff76-48ce-a5fa-a3ef1fe18539)

Anyway, my idea of ​​"cleaning" the texture didn't work out 100%...

Would there be a way to 100% remove the texture from a server?
Ex:
```yaml
global:
  pack: none #this apply default texture pack from minecraft
```

**Comment by Phoenix616** [comment]
@Logikoz That workaround should not be necessary because if no pack is configured globally nor for the server then the pack will be removed from the client in 1.20.3+, that's what the message is about. If it isn't working for you then please provide your full log too.

**Comment by Logikoz** [comment]
@Phoenix616 here full log
[proxy.log.txt](https://github.com/Phoenix616/ResourcepacksPlugins/files/15055940/proxy.log.txt)

**Comment by Phoenix616** [comment]
Hm, as far as I can tell your log looks fine. Will have to do some testing myself to see if I can reproduce it.

**Comment by Logikoz** [comment]
i recommend to use this config:

```yaml
debug: true
default-language: en
disable-metrics: false
autogeneratehashes: true
append-hash-to-url: true
usepack-is-temporary: true
stored-packs-override-assignments: false
permanent-pack-remove-time: 30
use-auth-plugin: false
packs:
  mmorpg:
    url: https://download.mc-packs.net/pack/0488ea8fefa4484a4721e14ffcfaed050ce8cdbb.zip
    hash: 0488ea8fefa4484a4721e14ffcfaed050ce8cdbb
    uuid: 21234567-89ab-cdef-0123-456789abcdef
    format: 1
    version: "1.20"
    restricted: false
    permission: bungeeresourcepacks.pack.mmorpg
  default:
    url: http://cdn.moep.tv/files/Empty.zip
    hash: 01517226212d27586ea0c5d6aff1aa5492dd2484
    format: 1
    version: "1.20"
    restricted: false
    permission: bungeeresourcepacks.pack.default
global:
  pack: default
servers:
  survival_mmorpg:
    packs:
    - mmorpg
```
