### ISSUE TITLE
World Resourcepacks assignments are overwritten by Velocity Resourcepacks

### ISSUE THREAD

**Issue by nx5314** [Phoenix616/ResourcepacksPlugins#91]
### What is happening?

When using the Velocity Resourcepacks plugin alongside the World Resourcepacks plugin, the Velocity plugin sends a resource pack assignment (or clear command) immediately after the World plugin assigns a pack based on the player's current world. Even when the Velocity plugin is configured with no specific assignment, it clears the player's resource pack right after the World plugin’s assignment upon server/world travel.

### What did you expect to happen?

World Resourcepacks assignments should take priority over Velocity Resourcepacks assignments, or at least not be cleared when none is assigned in Velocity Resourcepacks.

### Version

World and Velocity: 1.9.0-SNAPSHOT (build 615)

### Config

```YAML
Velocity:
debug: true
default-language: en
disable-metrics: false
autogeneratehashes: true
append-hash-to-url: false
usepack-is-temporary: true
stored-packs-override-assignments: false
permanent-pack-remove-time: 30
use-auth-plugin: false
empty:
  url: http://cdn.moep.tv/files/Empty.zip
  hash: 01517226212d27586ea0c5d6aff1aa5492dd2484
global:
  pack: empty
  send-delay: 5
servers:
  Lobby:
    packs:
    - whimscape
    - authenticshadows
  Minecraftia:
    pack: dokucraft
  # GameWorld:
    # pack: GameWorldpack
  Drehmal:
    pack: drehmalpack
  Roguecraft:
    pack: roguecraftpack
  Adventure:
    pack: empty
useauth: false
packs:
  AuthenticShadows:
    url: https://cdn.modrinth.com/data/kWgq7eAt/versions/2g7fYcvg/Authentic%20Shadows_1.21%2B.zip
    uuid: 6590f623-dd15-3824-84f7-6e07cef05e77
    hash: 25d7c55757b3bb3e7df2caea42089725cd4d346c
    restricted: false
    permission: velocityresourcepacks.pack.AuthenticShadows
  Ashen:
    url: https://cdn.modrinth.com/data/LSmohupN/versions/bZooY5Fe/Ashen_16x.zip
    uuid: 4af26b77-1ba6-3e4b-99ab-de75b90d46c4
    hash: 88116333c1c1f9a7d5591219eb8162dce132779e
    restricted: false
    permission: velocityresourcepacks.pack.Ashen
  Reimagined:
    url: https://cdn.modrinth.com/data/ta5dy0aA/versions/KlvNsbQZ/%C2%A7aReimagined%C2%A70_%C2%A78%5Bv1.49.2%5D%C2%A70.zip
    uuid: 1cbe799a-9868-3349-8665-ebfe8abaa156
    hash: a744f6e91498e6c19b28126b387ca5b91996f8ab
    restricted: false
    permission: velocityresourcepacks.pack.Reimagined
  DrehmalPack:
    url: http://Minecraftia.ddns.net:25555/Primordial_Pack_v2.2.2.zip
    uuid: d3a95f6e-33f4-37a4-a7d2-ca7127fdc952
    hash: 1f9b94bf0793635e3ba1cdda12a427ba3fdb68fc
    restricted: false
    permission: velocityresourcepacks.pack.DrehmalPack
  RoguecraftPack:
    url: https://cdn.modrinth.com/data/cTrc3jId/versions/IaJPlbBd/Roguecraft%201.3.4%20-%20Resource%20Pack.zip
    uuid: dd09727f-d147-3d6d-adfa-180bd31e1e44
    hash: a730ac30667bf3951d2f664cc29ea7c2eef0ba80
    restricted: false
    permission: velocityresourcepacks.pack.RoguecraftPack
  Whimscape:
    url: https://cdn.modrinth.com/data/4YkvO5Rp/versions/TDr6olme/Whimscape_1.20.2-1.21.5_r1.zip
    uuid: 2bcd7858-7152-3a61-afda-d3f1621905b1
    hash: f392fd9a8524db3f3d106702bb08335bc9c91592
    restricted: false
    permission: velocityresourcepacks.pack.Whimscape

GameWorld server:
debug: true
default-language: en
disable-metrics: false
autogeneratehashes: true
append-hash-to-url: false
usepack-is-temporary: true
stored-packs-override-assignments: false
permanent-pack-remove-time: 30
use-auth-plugin: false
empty:
  url: http://cdn.moep.tv/files/Empty.zip
  hash: 01517226212d27586ea0c5d6aff1aa5492dd2484
global:
  pack: empty
  send-delay: 5
worlds:
  Game:
    packs:
    - whimscape
    - authenticshadows
  Tree_Grid_World_1:
    packs:
    - authenticshadows
    - GameWorldPack
  Wolfs_Head_Island:
    packs:
    - authenticshadows
    - GameWorldPack
packs:
  GameWorldPack:
    url: http://hypotheticalserver.net/GameWorldPack.zip
    uuid: 86c8f6b7-05cf-3d0d-9277-ca395db29320
    hash: 97090d4eae428696a9fa0fbc4a47a1221458aca3
    restricted: false
    permission: worldresourcepacks.pack.GameWorldPack
  AuthenticShadows:
    url: https://cdn.modrinth.com/data/kWgq7eAt/versions/2g7fYcvg/Authentic%20Shadows_1.21%2B.zip
    uuid: 6590f623-dd15-3824-84f7-6e07cef05e77
    hash: 25d7c55757b3bb3e7df2caea42089725cd4d346c
    restricted: false
    permission: velocityresourcepacks.pack.AuthenticShadows
  Ashen:
    url: https://cdn.modrinth.com/data/LSmohupN/versions/bZooY5Fe/Ashen_16x.zip
    uuid: 4af26b77-1ba6-3e4b-99ab-de75b90d46c4
    hash: 88116333c1c1f9a7d5591219eb8162dce132779e
    restricted: false
    permission: velocityresourcepacks.pack.Ashen
  Reimagined:
    url: https://cdn.modrinth.com/data/ta5dy0aA/versions/KlvNsbQZ/%C2%A7aReimagined%C2%A70_%C2%A78%5Bv1.49.2%5D%C2%A70.zip
    uuid: 1cbe799a-9868-3349-8665-ebfe8abaa156
    hash: a744f6e91498e6c19b28126b387ca5b91996f8ab
    restricted: false
    permission: velocityresourcepacks.pack.Reimagined
  Whimscape:
    url: https://cdn.modrinth.com/data/4YkvO5Rp/versions/TDr6olme/Whimscape_1.20.2-1.21.5_r1.zip
    uuid: 2bcd7858-7152-3a61-afda-d3f1621905b1
    hash: f392fd9a8524db3f3d106702bb08335bc9c91592
    restricted: false
    permission: velocityresourcepacks.pack.Whimscape
```

### Server/system Version

velocity-3.4.0-SNAPSHOT-495 | purpur-1.21.4-2416 | Win11 23H2 22631.5189

### Log

```shell
Sections of relevant log and comments:

[18:43:49] [Server thread/INFO]: Username joined the game  <joining server on world Game>
[18:43:49] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] Username matched assignment Game due to main packs
[18:43:49] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] (proxy)server sent command to remove the pack Whimscape from player Username
[18:43:49] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] (proxy)server sent command to remove the pack AuthenticShadows from player Username
[18:43:49] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] (proxy)server sent command to clear the pack of player Username

<the velocity plugin erroneously clears the resourcepacks>

[18:44:13] [Server thread/INFO]: Username issued server command: /wrp reload resend

[18:44:13] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] Username matched assignment Game due to main packs
[18:44:13] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] Send pack Whimscape (https://cdn.modrinth.com/data/4YkvO5Rp/versions/TDr6olme/Whimscape_1.20.2-1.21.5_r1.zip) to Username
[18:44:13] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] Send pack AuthenticShadows (https://cdn.modrinth.com/data/kWgq7eAt/versions/2g7fYcvg/Authentic%20Shadows_1.21%2B.zip) to Username
[18:44:46] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] (proxy)server sent pack Whimscape (https://cdn.modrinth.com/data/4YkvO5Rp/versions/TDr6olme/Whimscape_1.20.2-1.21.5_r1.zip) to player Username
[18:44:46] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] (proxy)server sent pack AuthenticShadows (https://cdn.modrinth.com/data/kWgq7eAt/versions/2g7fYcvg/Authentic%20Shadows_1.21%2B.zip) to player Username

<now the user has the correct resourcepacks loaded>

<returned to lobby server>

[18:44:46] [Server thread/INFO]: Username joined the game  <joining server on world Game>
[18:44:47] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] Username matched assignment Game due to main packs
[18:44:47] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] (proxy)server sent command to remove the pack Whimscape from player Username
[18:44:47] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] (proxy)server sent command to remove the pack AuthenticShadows from player Username
[18:44:47] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] (proxy)server sent command to clear the pack of player Username
```

### What other programs/plugins are you running?

On Velocity:
Advanced-Portals-Spigot-2.5.0, floodgate-velocity [2.2.4-SNAPSHOT (b116-0e3163c)], Geyser-Velocity [2.7.0-b810 (git-master-91ca77d)], MapModCompanion [0.10.0], minimotd-velocity-2.1.5, TAB v5.2.0, VelocityClearChat-1.0.1, VelocityResourcepacks [1.9.0-SNAPSHOT (build 615)], ViaBackwards-5.3.2, ViaVersion-5.3.2

On Lobby server:
AdvancedBackups-spigot-1.21-3.7.1, Advanced-Portals-Spigot-2.5.0, AxiomPaper-4.0.4-for-MC1.21.4, bluemap-5.7-spigot, BlueMapFilteredEntities-1.0, BlueMapFloodgate-3.5, BuildersUtilities-1.8.3, DistantHorizonsSupport-Bukkit-Paper-0.9.0-SNAPSHOT-1.21.4, EssentialsX-2.21.0, EssentialsXChat-2.21.0, EssentialsXDiscord-2.21.0, EssentialsXSpawn-2.21.0, FastAsyncWorldEdit-Paper-2.13.1-SNAPSHOT-1094, floodgate-spigot [2.2.4-SNAPSHOT (b116-0e3163c)], GSit-2.3.2, hexnicks-3.1.2, MapModCompanion [0.10.0], OpenInv [5.1.9], packetevents-spigot-2.7.0, PlaceholderAPI-2.11.6, ProtocolLib [5.3.0], PurpurExtras-1.34.5, Spawn-2.4.1, TAB v5.2.0, TAB-Bridge.v6.0.2, VaultUnlocked-2.10.0, ViaBackwards-5.3.2, ViaVersion-5.3.2, worldguard-bukkit-7.0.13-dist, WorldGuardExtraFlags [4.2.4-SNAPSHOT]

On Main relevant server:
Paper Plugins (6):
AdvancedServerList [5.5.1], BKCommonLib [1.21.4-v1-snapshot], CraftBook5 [5.0.0-snapshot+4886], FancyNpcs [2.4.4], LANBroadcaster [2.3.1], Typewriter [0.8.0-beta-157]

Bukkit Plugins (52):
AnimatedArchitecture [0.7.2], AxiomPaper [4.0.4], BlueMap [5.7], BlueMapFilteredEntities [1.0], BlueMapFloodgate [3.5], BuildersUtilities [1.8.3], Chunky [1.4.36], CraftBook [3.10.12]
DHSupport [0.9.0-snapshot], DoorsReloaded [1.3.1], eBackup [1.3.1], Essentials [2.21.0], EssentialsChat [2.21.0], EssentialsDiscord [2.21.0], EssentialsSpawn [2.21.0], FastAsyncWorldEdit [2.13.1-snapshot-1092], floodgate [2.24-snapshot], GSit [2.3.2], Harbor [1.6.3], HexNicks [3.1.2], HoloMobHealth [2.3.13.0], LightCleaner [1.19.3-v1], LuckPerms [5.4.145], MapModCompanion [0.10.0], Multiverse-Core [4.3.16], Multiverse-NetherPortals [4.2.3], Multiverse-Portals [4.2.3], Multiverse-SignPortals [4.3.0], MythicMobs [5.8.2-6a2683d7], NBTAPI [2.15.0], OpenInv [5.1.9], packetevents [2.7.0], PlaceholderAPI [2.11.6], PreventStabby [1.11.1], ProtocolLib [5.3.0], PurpurExtras [1.34.5], SmoothTimber [1.27.4], TAB [5.2.0], TAB-Bridge [6.0.2], TeaksTweaks [2.0.7-mc1.21.4], Vault [2.10.0], ViaBackwards [5.3.2], ViaVersion [5.3.2], VoxelSniper [8.13.0], WorldGuard [7.0.13+82fdc65], WorldGuardExtraFlags [4.2.4-snapshot], WorldResourcepacks [1.9.0-snapshot (build615)], ZNPCsPlus [2.1.0-snapshot]

**Comment by nx5314** [comment]
Okay, so I'm either going crazy or it actually _does_ start working correctly if the proxied server is fully restarted, rather than reloading the config for World Resourcepacks on the proxied server.

So still not working as intended, but this is the current workaround.

**Comment by Phoenix616** [comment]
You need to specify the packs you send with WRP as optional-packs on the proxy in the global assignment (or per-server one if there is one for that server) for it to not remove it.

**Comment by nx5314** [comment]
Oh, is that what you mean by "List of packs to not replace if the user already has them" in the config comment?  It's not the clearest description in that case, if I might suggest a spot for clarification.

**Comment by Phoenix616** [comment]
Yes, the `optional-packs` list. If you have a better description then sure, it's pretty clear for me.

**Comment by nx5314** [comment]
```YAML
global:
  # 1. The "pack" entry defines a global resourcepack (in this case, "globalpack")
  #    which serves as the default pack for players.
  #
  # 2. The "optional-packs" list is used to select a fallback pack (from top to bottom)
  #    if a user does not have the permission or the correct version to use the default
  #    pack, or if no resourcepack is specified in the "pack" entry.
  #
  # 3. The "optional-packs" list specifies resourcepacks that will NOT be replaced if a
  #    player already has them loaded.
  #
  # 4. Additionally, in configurations where the World Resourcepacks plugin is active on
  #    one or more servers in the Velocity network, the "optional-packs" list acts as an
  #    allow-list. That means when a player travels to a server managed by the
  #    World Resourcepacks plugin, only the resourcepacks listed here are accepted and 
  #    applied, others will be cleared.
  # Define a global pack:
  pack: globalpack
  # Define a list of optional packs:
  optional-packs:
    - lobbypack
```
Something along these lines if you like and consider this accurate?

**Comment by Phoenix616** [comment]
That feels really long and the 4. point unnecessary as the first ones already explain the same thing as it's not acting as an allow list special to WRP, it uses the exact same logic no matter where the pack was sent from. As in packs that are neither in the `packs` list nor the `optional-packs` list are removed.

**Comment by nx5314** [comment]
I mean yeah it is longer than it needs to be, my point just being that from the perspective of a new user it isn't inherently obvious how this behaviour works and can stand to have a more thorough explanation.

```YAML
global:
  # - "pack" defines the default resource pack ("globalpack").
  # - "optional-packs" is a prioritized list (top to bottom) where:
  #     • Installed packs are preserved.
  #     • If no main pack is set or if a user lacks the necessary permissions or version,
  #       an optional pack is selected.
  # - Any packs not listed here are removed.
  #
  # - In a Velocity network running the World Resourcepacks plugin on any servers,
  #   the same logic applies—only packs in these lists are kept.
  # Define a global pack:
  pack: globalpack
  # Define a list of optional packs:
  optional-packs:
    - lobbypack
```
Would this be more appropriate? Just want to save other people time if they have the same confusion I did.
